### ISSUE TITLE
configuration for component generation

### ISSUE THREAD

**Issue by newtonmunene99** [natemoo-re/vscode-stencil-tools#6]
How do I configure the tool to generate scss instead of css and shadow: true

**Comment by paulcpederson** [comment]
@newtonmunene99 I just figured this out, it's in settings. Go to: `Preferences: Open Workpace Settings` and on the left you'll see `Extensions`. Inside the extensions list there should be a `Stencil Tools config` option. If you click that (or scroll to it) you can edit both of those I think.
